### ISSUE TITLE
Programmatical download links

### ISSUE THREAD

**Issue by lambdaofgod** [sdadas/polish-nlp-resources#1]
Could you please provide links to GDrive files that enable getting them by wget/curl, or host them somewhere else?

Google Drive makes programmatic downloading of uploaded files using wget/curl a huge pain in the ass, and if you overcame that, I'm sure more people would use your library.

**Comment by sdadas** [comment]
@lambdaofgod I'd love to but currently I can only use free hosting services. Google Drive unfortunately does't support generating direct links for large files. Do you know of any file hosting provider which supports that feature?

**Comment by lambdaofgod** [comment]
Have you thought of using [git lfs](https://git-lfs.github.com)? If you don't have time to investigate that, I could try to use it and replace download links

**Comment by sdadas** [comment]
@lambdaofgod Thanks for the response. There is a [strict limit of 100MB](https://help.github.com/en/articles/what-is-my-disk-quota) per file on GitHub so lfs is not an option. 
As an alternative, I created a release for this repository where one can upload files up to 2GB. You can now download all models except FastText (which is larger than 2GB) using github links.

https://github.com/sdadas/polish-nlp-resources/releases
