### ISSUE TITLE
Error with unpacking high dimensional word vectors

### ISSUE THREAD

**Issue by Rurson** [sdadas/polish-nlp-resources#5]
When i wanted to unpack zipped files, I got an error: `error:  invalid compressed data to inflate`. I got this error only with these embeddings:
* fasttext_500_3_polish.zip
* fasttext_800_3_polish.zip
* word2vec_800_3_polish.zip

also got CRC error with file:
* fasttext_500_3_polish.bin.wv.vectors_vocab.npy

I used zip, 7z on linux and winrar on Windows to unpack so I think these files are packed incorrectly.

**Comment by sdadas** [comment]
Thanks for the information. The problem is probably related to OneDrive. I've had problems before with OneDrive damaging large zip uploads.

Fortunately I still have local copies of these embeddings so I'll try to reupload them soon.

**Comment by Rurson** [comment]
Thanks for quick replay. I'll be waiting for it :smile:

**Comment by sdadas** [comment]
I've updated the repository with new links to the models.
